### PR TITLE
continuous_JSD: return nan if np.linalg.LinAlgError

### PR DESCRIPTION
**Pull request by skinnider**
As discussed, preferable to fail/return nan than add random noise

### CODE REVIEW

**Comment by vineetbansal** [comment]
Ah - looks like a pre-commit error. We never documented this before, but I've now created a [wiki](https://github.com/skinniderlab/CLM/wiki/Developer-Setup) page for CLM that explains (towards the end) what its all about. Its standard language that we've used in a few projects now.

**Comment by skinnider** [comment]
Running this locally:
```
(base) michaelskinnider@vpn12-client-172-20-202-108 CLM % pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/anaconda3/bin/python', '-mvirtualenv', '/Users/michaelskinnider/.cache/pre-commit/repoaaeyk5pg/py_env-python3.10', '-p', 'python3.10')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'
stderr: (none)
Check the log at /Users/michaelskinnider/.cache/pre-commit/pre-commit.log
```

**Comment by skinnider** [comment]
I think this is now failing because some of the values in the test suite assume the addition of random noise to calculate the JSD?

**Comment by vineetbansal** [comment]
yes - in these cases we update the test data after code review, and I've done so now in this branch. Once this passes, we can merge this.

**Pull request merged**
